name: Trigger CodeBuild to Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  trigger-codebuild:
    runs-on: ubuntu-latest
    permissions:
          id-token: write
          contents: read

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # e.g., us-east-1

      # Trigger the CodeBuild Project
      - name: Trigger AWS CodeBuild
        run: |
          aws codebuild start-build --project-name project3
